### ISSUE TITLE
Class "Filament\PluginServiceProvider" not found

### ISSUE THREAD

**Issue by goyne** [husam-tariq/filament-timepicker#10]
Installed this plugin on a fresh Filament environment and this error is returned:

Class "Filament\PluginServiceProvider" not found

Laravel: v11.2.0
Filament: v3.2.62
Timepicker: v1.0.4

**Comment by abdulmannans-joistic** [comment]
Any solution on this?

**Comment by yosefmiller** [comment]
Timepicker v3 was rewritten for Filament v3, however it is incompatible with Laravel v11:

> laravel/framework replaces illuminate/contracts and thus cannot coexist with it.

The issue is with the composer requirement `"illuminate/contracts": "^10.0"`. Looks like it needs to be removed.

**Comment by husam-tariq** [comment]
please try now we have update the package
